services:
  # Development environment
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: npm run watch

  # Build service that builds the extension and serves it
  build-and-serve:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm run build && nginx -g 'daemon off;'"
    ports:
      - "8080:80"

  # Production service (requires pre-built dist/ folder)
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production